SHELL := /bin/bash

# Public development credentials generated by Anvil.
# These values are intentionally restricted to the local chain at 127.0.0.1.
ANVIL_RPC_URL := http://127.0.0.1:8545
ANVIL_CHAIN_ID := 31337
ANVIL_PRIVATE_KEY := 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
ANVIL_ACCOUNT := 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
COINFLIP_STATE_FILE := .anvil/coinflip.env

export ANVIL_PRIVATE_KEY

.PHONY: help test anvil local-check coinflip-deploy coinflip-step coinflip-solve coinflip-status

help:
	@echo "Available commands:"
	@echo "  make test             Run the complete Forge test suite"
	@echo "  make anvil            Start a fresh local Anvil node"
	@echo "  make coinflip-deploy  Deploy CoinFlip and its solver locally"
	@echo "  make coinflip-step    Submit one local CoinFlip prediction"
	@echo "  make coinflip-solve   Submit ten predictions in separate blocks"
	@echo "  make coinflip-status  Read the local consecutive-win count"

test:
	forge test

anvil:
	anvil --host 127.0.0.1 --port 8545 --chain-id $(ANVIL_CHAIN_ID)

local-check:
	@chain_id=$$(cast chain-id --rpc-url $(ANVIL_RPC_URL) 2>/dev/null) || { \
		echo "Local Anvil is not running. Start it with: make anvil"; \
		exit 1; \
	}; \
	test "$$chain_id" = "$(ANVIL_CHAIN_ID)" || { \
		echo "Refusing to continue: expected local chain ID $(ANVIL_CHAIN_ID), received $$chain_id"; \
		exit 1; \
	}; \
	account=$$(cast wallet address --private-key $(ANVIL_PRIVATE_KEY)); \
	test "$$account" = "$(ANVIL_ACCOUNT)" || { \
		echo "Refusing to continue: unexpected local development account"; \
		exit 1; \
	}

coinflip-deploy: local-check
	@mkdir -p .anvil
	forge script script/03_CoinFlip/DeployCoinFlip.s.sol:DeployCoinFlip \
		--rpc-url $(ANVIL_RPC_URL) \
		--broadcast

coinflip-step: local-check
	@test -f $(COINFLIP_STATE_FILE) || { \
		echo "Local CoinFlip deployment not found. Run: make coinflip-deploy"; \
		exit 1; \
	}
	@set -a; source $(COINFLIP_STATE_FILE); set +a; \
	cast rpc anvil_mine 0x1 --rpc-url $(ANVIL_RPC_URL) >/dev/null; \
	forge script script/03_CoinFlip/SolveCoinFlip.s.sol:SolveCoinFlip \
		--rpc-url $(ANVIL_RPC_URL) \
		--broadcast

coinflip-solve: local-check
	@test -f $(COINFLIP_STATE_FILE) || { \
		echo "Local CoinFlip deployment not found. Run: make coinflip-deploy"; \
		exit 1; \
	}
	@set -e; set -a; source $(COINFLIP_STATE_FILE); set +a; \
	current_wins=$$(cast call $$COINFLIP_TARGET "consecutiveWins()(uint256)" --rpc-url $(ANVIL_RPC_URL)); \
	test "$$current_wins" = "0" || { \
		echo "Expected a fresh deployment with 0 wins, received $$current_wins"; \
		echo "Restart Anvil and run make coinflip-deploy again."; \
		exit 1; \
	}; \
	for round in $$(seq 1 10); do \
		echo "Submitting local prediction $$round/10"; \
		cast rpc anvil_mine 0x1 --rpc-url $(ANVIL_RPC_URL) >/dev/null; \
		forge script script/03_CoinFlip/SolveCoinFlip.s.sol:SolveCoinFlip \
			--rpc-url $(ANVIL_RPC_URL) \
			--broadcast \
			-q; \
	done; \
	final_wins=$$(cast call $$COINFLIP_TARGET "consecutiveWins()(uint256)" --rpc-url $(ANVIL_RPC_URL)); \
	test "$$final_wins" = "10" || { \
		echo "Local solve did not reach 10 wins. Current value: $$final_wins"; \
		exit 1; \
	}; \
	echo "CoinFlip solved locally with $$final_wins consecutive wins."

coinflip-status: local-check
	@test -f $(COINFLIP_STATE_FILE) || { \
		echo "Local CoinFlip deployment not found. Run: make coinflip-deploy"; \
		exit 1; \
	}
	@set -a; source $(COINFLIP_STATE_FILE); set +a; \
	wins=$$(cast call $$COINFLIP_TARGET "consecutiveWins()(uint256)" --rpc-url $(ANVIL_RPC_URL)); \
	echo "CoinFlip consecutive wins: $$wins"
